/**
 * A class.
 * <br>
 * This is some <i>Italic</i> text.
 * <br>
 * This is also some <em>Italic</em> text.
 * <br>
 * This is some <b>bold</b> text.
 * <br>
 * This is also some <strong>bold</strong> text.
 * <br>
 * This text is <s>struck through</s>.
 * <br>
 * This text is <u>underlined</u>.
 * <br>
 * This is an ordered list:
 * <ol>
 *   <li>List Item 1</li>
 *   <li>List Item 2</li>
 * </ol>
 * <br>
 * <br>
 * This is an unordered list:
 * <ul>
 *   <li>List Item 1</li>
 *   <li>List Item 2</li>
 * </ul>
 */
public class TEST_HtmlTags {
    /**
     * A method.
     * <br>
     * This is some <i>Italic</i> text.
     * This is some <b>bold</b> text.
     * This text is <s>struck through</s>.
     * This text is <u>underlined</u>.
     * <li>List Item 1</li>.
     * <li>List Item 2</li>.
     * <ul>List Item 3</ul>.
     * <ul>List Item 4</ul>.
     */
    private static void doSomething() {
    }
}