export const AUTHOR: string = '@author';
export const DATE: string = '@date';
export const DEPRECATED: string = '@deprecated';
export const DESCRIPTION: string = '@description';
export const EXAMPLE: string = '@example';
export const EXCEPTION: string = '@exception';
export const GROUP: string = '@group '; // needed to include space to not match group-content
export const GROUP_CONTENT: string = '@group-content';
export const PARAM: string = '@param';
export const RETURN: string = '@return';
export const SEE: string = '@see';